export const px = (id: number, w = 900, h = 900) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=${w}&h=${h}`;

export const SIZE_SETS = {
  sneakers: ["UK 5", "UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11", "UK 12"],
  clothing: ["XS", "S", "M", "L", "XL", "2XL"],
  one: ["One Size"],
} as const;

export type SizeSetKey = keyof typeof SIZE_SETS;

export type SeedCategory = {
  slug: string;
  name: string;
  tagline: string;
  image: number;
  sortOrder: number;
  // Which department (see CATEGORY_GROUPS in lib/category-groups.ts) this nests under.
  group: string;
};

export type SeedProduct = {
  slug: string;
  name: string;
  brand: string;
  category: string;
  description: string;
  details: string[];
  images: number[];
  sizeSet: SizeSetKey;
  colorway: string;
  price: number;
  was?: number;
  rating: number;
  reviews: number;
  stock: number;
  featured?: boolean;
  isNew?: boolean;
  sold: number;
};

export type SeedTestimonial = {
  customerName: string;
  location: string;
  quote: string;
  rating: number;
  image: number;
  productName: string;
  sortOrder: number;
};

export const seedTestimonials: SeedTestimonial[] = [
  {
    customerName: "Lerato Mabaso",
    location: "Soweto, Gauteng",
    quote:
      "Ordered Jordan 1s on Tuesday and they landed Thursday morning. Original box, clean pair, and Tshidi kept me updated the whole way. She really is the plug.",
    rating: 5,
    image: 1649673,
    productName: "Air Jordan 1 Retro High",
    sortOrder: 1,
  },
  {
    customerName: "Sipho Khumalo",
    location: "Durban, KZN",
    quote:
      "I bought a tracksuit and a 12-piece pot set in one order. Everything arrived packed properly. This is my family's store now.",
    rating: 5,
    image: 16927318,
    productName: "adidas tracksuit + Tefal pot set",
    sortOrder: 2,
  },
  {
    customerName: "Naledi Pillay",
    location: "Pretoria, Gauteng",
    quote:
      "The size exchange was painless — wrong size on Monday, correct size by Friday. Customer service on WhatsApp is unmatched.",
    rating: 5,
    image: 13562801,
    productName: "New Balance 550",
    sortOrder: 3,
  },
];

export const seedCategories: SeedCategory[] = [
  // ---- Shoes ----
  { slug: "sneakers", name: "Sneakers", tagline: "Certified heat, straight from the plug", image: 11718014, sortOrder: 1, group: "shoes" },
  { slug: "formal-shoes", name: "Formal", tagline: "Loafers, heels & office ready", image: 27204305, sortOrder: 2, group: "shoes" },
  { slug: "sandals", name: "Sandals", tagline: "Slides, flats & open shoes for summer", image: 19461552, sortOrder: 3, group: "shoes" },

  // ---- Clothing ----
  { slug: "pants-bottoms", name: "Pants & Bottoms", tagline: "Jeans, joggers & everyday bottoms", image: 18416501, sortOrder: 1, group: "clothing" },
  { slug: "t-shirts", name: "T-Shirts", tagline: "Everyday tops & golfers", image: 19461552, sortOrder: 2, group: "clothing" },
  { slug: "two-piece-sets", name: "Two-Piece Sets", tagline: "Matching two-piece fits", image: 19461583, sortOrder: 3, group: "clothing" },

  // ---- Accessories ----
  { slug: "bags", name: "Bags", tagline: "Totes, crossbodies & travel", image: 27174573, sortOrder: 1, group: "accessories" },
  { slug: "watches", name: "Watches", tagline: "Wrist game on point", image: 8839887, sortOrder: 2, group: "accessories" },
  { slug: "jewelry", name: "Jewellery", tagline: "Rings, chains & earrings", image: 8839887, sortOrder: 3, group: "accessories" },

  // ---- House & Home ----
  { slug: "pots-pans", name: "Pots & Pans", tagline: "Pots, pans & kitchen kit that lasts a lifetime", image: 16927367, sortOrder: 1, group: "house-home" },
  { slug: "furniture", name: "Furniture", tagline: "Dining, lounge & living upgrades", image: 5262675, sortOrder: 2, group: "house-home" },
];

export const seedProducts: SeedProduct[] = [
  // ---------------- SNEAKERS ----------------
  {
    slug: "jordan-1-retro-high-court-heat",
    name: "Air Jordan 1 Retro High 'Court Heat'",
    brand: "Jordan",
    category: "sneakers",
    description:
      "The silhouette that started it all. Premium tumbled leather, a padded ankle collar and that unmistakable Wings logo. Comes boxed with original tags and a Tshidi the Plug authenticity card.",
    details: ["Full-grain leather upper", "Air-Sole cushioning unit", "Original box + spare laces", "100% authentic guarantee"],
    images: [11718014, 16923479, 12010216],
    sizeSet: "sneakers",
    colorway: "Black / Varsity Red / White",
    price: 3499,
    was: 3999,
    rating: 4.9,
    reviews: 214,
    stock: 12,
    featured: true,
    isNew: true,
    sold: 340,
  },
  {
    slug: "nike-air-force-1-triple-white",
    name: "Nike Air Force 1 '07 Triple White",
    brand: "Nike",
    category: "sneakers",
    description:
      "The cleanest pair in any rotation. Crisp white leather, perforated toe box and a chunky Air cushioned sole that keeps you comfortable from taxi rank to campus.",
    details: ["Leather upper with perforations", "Encapsulated Air unit", "Non-marking rubber outsole", "Unisex sizing"],
    images: [9507116, 4296075, 24702077],
    sizeSet: "sneakers",
    colorway: "Triple White",
    price: 2199,
    rating: 4.8,
    reviews: 402,
    stock: 30,
    featured: true,
    sold: 812,
  },
  {
    slug: "adidas-forum-low-royal",
    name: "adidas Forum Low 'Royal Blue'",
    brand: "adidas",
    category: "sneakers",
    description:
      "An '80s hoops icon rebuilt for the street. Bold blue overlays, the signature ankle strap and a comfy sockliner for all-day wear.",
    details: ["Leather and synthetic upper", "Iconic X-strap closure", "Rubber cupsole", "Ships in original box"],
    images: [19869753, 19869759],
    sizeSet: "sneakers",
    colorway: "Royal Blue / Cloud White",
    price: 1899,
    was: 2299,
    rating: 4.7,
    reviews: 158,
    stock: 18,
    featured: true,
    sold: 264,
  },
  {
    slug: "new-balance-550-grey-suede",
    name: "New Balance 550 Grey Suede",
    brand: "New Balance",
    category: "sneakers",
    description:
      "Retro basketball lines with a premium suede build. The quiet flex — pairs with everything from cargos to a tailored suit.",
    details: ["Suede and mesh upper", "Cushioned EVA midsole", "Padded collar", "True to size fit"],
    images: [30755567, 27113471],
    sizeSet: "sneakers",
    colorway: "Grey / White",
    price: 2749,
    rating: 4.9,
    reviews: 97,
    stock: 14,
    isNew: true,
    featured: true,
    sold: 143,
  },
  {
    slug: "nike-dunk-low-red-alert",
    name: "Nike Dunk Low 'Red Alert'",
    brand: "Nike",
    category: "sneakers",
    description:
      "Low-profile, high impact. Colour-blocked leather panels in fire red with a crisp white base — a guaranteed head-turner.",
    details: ["Leather overlays", "Foam midsole", "Classic Dunk outsole pattern", "Boxed with tags"],
    images: [10963373, 12010216],
    sizeSet: "sneakers",
    colorway: "University Red / White",
    price: 2899,
    rating: 4.8,
    reviews: 176,
    stock: 9,
    isNew: true,
    sold: 221,
  },
  {
    slug: "puma-suede-classic-volt",
    name: "PUMA Suede Classic 'Volt'",
    brand: "PUMA",
    category: "sneakers",
    description:
      "A street staple since '68. Soft suede upper with the formstrip in a punchy volt green — comfortable straight out the box.",
    details: ["Soft suede upper", "Lightly padded collar", "Rubber outsole", "Unisex"],
    images: [19882430, 19882424],
    sizeSet: "sneakers",
    colorway: "Volt / Black",
    price: 1499,
    rating: 4.6,
    reviews: 88,
    stock: 25,
    sold: 190,
  },
  {
    slug: "converse-chuck-70-canvas",
    name: "Converse Chuck 70 High Canvas",
    brand: "Converse",
    category: "sneakers",
    description:
      "The heritage Chuck with a higher rubber foxing, thicker canvas and extra cushioning. Timeless with jeans or a tracksuit.",
    details: ["Heavyweight canvas", "OrthoLite cushioning", "Vintage licence plate", "Unisex sizing"],
    images: [4296075, 24702077],
    sizeSet: "sneakers",
    colorway: "Optical White",
    price: 1299,
    rating: 4.7,
    reviews: 132,
    stock: 22,
    sold: 305,
  },
  {
    slug: "vans-old-skool-metallic",
    name: "Vans Old Skool Metallic",
    brand: "Vans",
    category: "sneakers",
    description:
      "The classic side-stripe skate shoe with a metallic silver twist. Padded collar, waffle outsole, endless grip.",
    details: ["Suede and canvas", "Signature waffle outsole", "Padded collars", "Reinforced toe cap"],
    images: [27113471, 19882433],
    sizeSet: "sneakers",
    colorway: "Metallic Silver",
    price: 1649,
    rating: 4.6,
    reviews: 64,
    stock: 16,
    sold: 118,
  },
  {
    slug: "levis-court-sneaker-sunset",
    name: "Levi's Court Sneaker 'Sunset'",
    brand: "Levi's",
    category: "sneakers",
    description:
      "Clean court silhouette in a warm sunset tone. Lightweight, everyday-friendly and easy on the pocket.",
    details: ["Vegan leather upper", "Cushioned footbed", "Contrast branding", "Everyday wear"],
    images: [14703446],
    sizeSet: "sneakers",
    colorway: "Sunset Orange / White",
    price: 1199,
    was: 1599,
    rating: 4.5,
    reviews: 41,
    stock: 20,
    sold: 87,
  },
  {
    slug: "reebok-club-c-marble",
    name: "Reebok Club C 85 'Marble'",
    brand: "Reebok",
    category: "sneakers",
    description:
      "Tennis-court heritage in soft leather. The everyday clean sneaker for people who don't do loud.",
    details: ["Soft garment leather", "Die-cut EVA midsole", "Low-cut design", "Classic Club C outsole"],
    images: [24702077, 30755567],
    sizeSet: "sneakers",
    colorway: "Chalk / Navy",
    price: 1750,
    rating: 4.7,
    reviews: 73,
    stock: 21,
    sold: 156,
  },
  {
    slug: "jordan-1-low-fragment-style",
    name: "Air Jordan 1 Low 'Fragment Style'",
    brand: "Jordan",
    category: "sneakers",
    description:
      "Low-top Jordan energy with tri-colour blocking. One of our fastest movers — restocked monthly and it never lasts.",
    details: ["Premium leather", "Air cushioning", "Low-cut collar", "Authenticity card included"],
    images: [16923479, 11718014],
    sizeSet: "sneakers",
    colorway: "White / Royal / Black",
    price: 3199,
    rating: 4.9,
    reviews: 121,
    stock: 7,
    featured: true,
    sold: 268,
  },
  {
    slug: "nike-air-max-heat-pack",
    name: "Nike Air Max 'Heat Pack'",
    brand: "Nike",
    category: "sneakers",
    description:
      "Visible Air, bold orange accents and a chunky retro runner shape. Built for comfort on long days.",
    details: ["Mesh and synthetic upper", "Visible Max Air unit", "Rubber waffle outsole", "Boxed"],
    images: [12010216, 10963373],
    sizeSet: "sneakers",
    colorway: "Total Orange / Sail",
    price: 2999,
    was: 3299,
    rating: 4.8,
    reviews: 95,
    stock: 11,
    isNew: true,
    sold: 174,
  },

  // ---------------- CLOTHING ----------------
  {
    slug: "adidas-two-piece-tracksuit",
    name: "adidas Two-Piece Tracksuit Set",
    brand: "adidas",
    category: "two-piece-sets",
    description:
      "Full matching set — zip-through jacket and tapered joggers with the classic three stripes. Ships as a complete set.",
    details: ["Jacket + joggers included", "Recycled polyester tricot", "Zip pockets", "Tapered leg with cuff"],
    images: [19461583, 18416501],
    sizeSet: "clothing",
    colorway: "Black / White",
    price: 1899,
    was: 2199,
    rating: 4.9,
    reviews: 143,
    stock: 24,
    featured: true,
    isNew: true,
    sold: 302,
  },
  {
    slug: "polo-pique-golfer",
    name: "Polo Signature Piqué Golfer",
    brand: "Polo",
    category: "t-shirts",
    description:
      "Breathable piqué cotton golfer with ribbed collar. Smart-casual done right for church, work or a Sunday braai.",
    details: ["Breathable piqué cotton", "Ribbed collar and cuffs", "Two-button placket", "Embroidered crest"],
    images: [5771897],
    sizeSet: "clothing",
    colorway: "Navy",
    price: 699,
    rating: 4.5,
    reviews: 89,
    stock: 44,
    sold: 276,
  },
  {
    slug: "adidas-graphic-tee-two-pack",
    name: "adidas Street Graphic Tee (2-Pack)",
    brand: "adidas",
    category: "t-shirts",
    description:
      "Two heavyweight cotton tees in one order. Boxy fit, dropped shoulders and screen-printed graphics that don't crack.",
    details: ["2 tees per pack", "220gsm cotton", "Boxy street fit", "Ribbed neckline"],
    images: [19461552, 18416501],
    sizeSet: "clothing",
    colorway: "Black + Bone",
    price: 599,
    was: 799,
    rating: 4.6,
    reviews: 128,
    stock: 50,
    sold: 388,
  },

  // ---------------- BAGS ----------------
  {
    slug: "michael-kors-croc-tote",
    name: "Michael Kors Croc-Embossed Tote",
    brand: "Michael Kors",
    category: "bags",
    description:
      "Structured croc-embossed tote with gold hardware and a roomy lined interior. Laptop fits, dignity intact.",
    details: ["Croc-embossed leather", "Gold-tone hardware", "Fits a 14\" laptop", "Dust bag included"],
    images: [27174572, 27174573],
    sizeSet: "one",
    colorway: "Chocolate Brown",
    price: 2499,
    was: 2999,
    rating: 4.9,
    reviews: 47,
    stock: 6,
    featured: true,
    sold: 74,
  },
  {
    slug: "guess-everyday-leather-shopper",
    name: "GUESS Everyday Leather Shopper",
    brand: "GUESS",
    category: "bags",
    description:
      "Soft two-tone shopper with detachable pouch. Big enough for the school run, smart enough for the office.",
    details: ["Vegan leather", "Detachable inner pouch", "Magnetic snap closure", "Adjustable shoulder strap"],
    images: [27127406, 4452386],
    sizeSet: "one",
    colorway: "Tan / Cream",
    price: 1899,
    rating: 4.7,
    reviews: 63,
    stock: 12,
    sold: 118,
  },
  {
    slug: "aldo-ivory-structured-handbag",
    name: "ALDO Ivory Structured Handbag",
    brand: "ALDO",
    category: "bags",
    description:
      "A crisp ivory handbag with a textured finish, top handle and removable crossbody strap. Wedding-season essential.",
    details: ["Textured PU finish", "Top handle + long strap", "Zip closure", "Interior slip pocket"],
    images: [27174565, 27174570],
    sizeSet: "one",
    colorway: "Ivory",
    price: 1650,
    rating: 4.8,
    reviews: 39,
    stock: 10,
    isNew: true,
    sold: 61,
  },
  {
    slug: "steve-madden-sage-crossbody",
    name: "Steve Madden Sage Crossbody",
    brand: "Steve Madden",
    category: "bags",
    description:
      "Compact crossbody in a fresh sage tone with a wide webbing strap. Hands free, style intact.",
    details: ["Wide adjustable strap", "Front flap with magnet", "Card slots inside", "Lightweight build"],
    images: [27174571],
    sizeSet: "one",
    colorway: "Sage Green",
    price: 1199,
    rating: 4.6,
    reviews: 44,
    stock: 17,
    sold: 92,
  },
  {
    slug: "guess-red-statement-handbag",
    name: "GUESS Red Statement Handbag",
    brand: "GUESS",
    category: "bags",
    description:
      "When the outfit is plain, the bag talks. Deep red finish with polished hardware and a structured silhouette.",
    details: ["Structured body", "Polished hardware", "Dual carry options", "Protective base studs"],
    images: [19869755],
    sizeSet: "one",
    colorway: "Racing Red",
    price: 1750,
    was: 2100,
    rating: 4.7,
    reviews: 35,
    stock: 9,
    sold: 58,
  },
  {
    slug: "aldo-evening-clutch",
    name: "ALDO Evening Clutch",
    brand: "ALDO",
    category: "bags",
    description:
      "Sleek black clutch with a hidden chain strap so you can switch from handheld to shoulder in a second.",
    details: ["Hidden chain strap", "Satin lining", "Fits phone + essentials", "Occasion ready"],
    images: [27035625],
    sizeSet: "one",
    colorway: "Black",
    price: 1450,
    rating: 4.5,
    reviews: 28,
    stock: 14,
    sold: 47,
  },

  // ---------------- FORMAL SHOES ----------------
  {
    slug: "aldo-tan-leather-loafers",
    name: "ALDO Tan Leather Loafers",
    brand: "ALDO",
    category: "formal-shoes",
    description:
      "Soft tan leather loafers with a low block heel. Office-ready, comfortable enough for a full day on your feet.",
    details: ["Genuine leather upper", "Cushioned insole", "Low stacked heel", "Slip-on fit"],
    images: [27204305],
    sizeSet: "sneakers",
    colorway: "Tan",
    price: 1399,
    rating: 4.7,
    reviews: 51,
    stock: 18,
    sold: 96,
  },
  {
    slug: "steve-madden-suede-loafers",
    name: "Steve Madden Chocolate Suede Loafers",
    brand: "Steve Madden",
    category: "formal-shoes",
    description:
      "Rich chocolate suede with a chunky lug sole. Smart-casual footwear that handles a Joburg winter.",
    details: ["Suede upper", "Lug rubber sole", "Padded collar", "Breathable lining"],
    images: [27204310],
    sizeSet: "sneakers",
    colorway: "Chocolate",
    price: 1299,
    was: 1599,
    rating: 4.6,
    reviews: 37,
    stock: 15,
    sold: 71,
  },
  {
    slug: "aldo-stiletto-court-heels",
    name: "ALDO Classic Stiletto Court Heels",
    brand: "ALDO",
    category: "formal-shoes",
    description:
      "The everyday black court heel — 9cm stiletto, pointed toe and a padded footbed that keeps you standing.",
    details: ["9cm stiletto heel", "Pointed toe", "Padded footbed", "Non-slip sole grip"],
    images: [27035625],
    sizeSet: "sneakers",
    colorway: "Black",
    price: 1199,
    rating: 4.5,
    reviews: 62,
    stock: 20,
    sold: 133,
  },

  // ---------------- WATCHES ----------------
  {
    slug: "fossil-onyx-chronograph",
    name: "Fossil Onyx Chronograph Watch",
    brand: "Fossil",
    category: "watches",
    description:
      "All-black chronograph with a brushed steel bracelet and three working sub-dials. Boxed with a 2-year warranty.",
    details: ["Stainless steel case & bracelet", "Chronograph movement", "50m water resistant", "2-year warranty"],
    images: [8839887, 16958879],
    sizeSet: "one",
    colorway: "Matte Black",
    price: 2899,
    was: 3299,
    rating: 4.8,
    reviews: 56,
    stock: 11,
    featured: true,
    sold: 88,
  },
  {
    slug: "fossil-heritage-leather-chrono",
    name: "Fossil Heritage Leather Chrono",
    brand: "Fossil",
    category: "watches",
    description:
      "Vintage-inspired chronograph on a genuine leather strap. Warm cream dial with luminous hands.",
    details: ["Genuine leather strap", "Luminous hands", "Domed mineral glass", "Gift box included"],
    images: [28977357, 6157408],
    sizeSet: "one",
    colorway: "Brown / Cream",
    price: 3499,
    rating: 4.9,
    reviews: 34,
    stock: 7,
    isNew: true,
    sold: 42,
  },
  {
    slug: "guess-silver-crystal-watch",
    name: "GUESS Silver Crystal-Marker Watch",
    brand: "GUESS",
    category: "watches",
    description:
      "Polished silver case set with crystal hour markers. Bright, glamorous and surprisingly light on the wrist.",
    details: ["Crystal hour markers", "Polished steel bracelet", "Quartz movement", "Adjustable links"],
    images: [15210883, 9261531],
    sizeSet: "one",
    colorway: "Silver",
    price: 2199,
    rating: 4.7,
    reviews: 48,
    stock: 13,
    sold: 77,
  },
  {
    slug: "sheffield-watch-box-set",
    name: "Sheffield Collector's Watch Box Set",
    brand: "Sheffield",
    category: "watches",
    description:
      "Three-watch gift set with a leather-look display case. The go-to present for graduations and 21sts.",
    details: ["3 watches included", "Display storage case", "Mixed leather + steel straps", "Gift wrapped free"],
    images: [38797596],
    sizeSet: "one",
    colorway: "Mixed",
    price: 4999,
    was: 5899,
    rating: 4.8,
    reviews: 22,
    stock: 5,
    sold: 31,
  },
  {
    slug: "casio-minimal-steel-dress-watch",
    name: "Casio Minimal Steel Dress Watch",
    brand: "Casio",
    category: "watches",
    description:
      "Slim, understated and reliable. A brushed steel dress watch that works with a suit or a hoodie.",
    details: ["Slim 8mm case", "Analogue quartz", "Mineral crystal", "5-year battery"],
    images: [16958879, 8839887],
    sizeSet: "one",
    colorway: "Steel",
    price: 1299,
    rating: 4.6,
    reviews: 84,
    stock: 24,
    sold: 156,
  },

  // ---------------- KITCHEN ----------------
  {
    slug: "tefal-12-piece-pot-set",
    name: "Tefal 12-Piece Stainless Steel Pot Set",
    brand: "Tefal",
    category: "pots-pans",
    description:
      "A complete kitchen starter in one box — five pots with tempered glass lids, a saucepan and a steamer insert. Induction friendly.",
    details: ["12 pieces including lids", "Encapsulated base for even heat", "Induction & gas compatible", "Dishwasher safe"],
    images: [16927367, 31557569],
    sizeSet: "one",
    colorway: "Stainless Steel",
    price: 3299,
    was: 3999,
    rating: 4.8,
    reviews: 96,
    stock: 16,
    featured: true,
    sold: 204,
  },
  {
    slug: "hart-cast-iron-potjie-no3",
    name: "Hart Cast Iron Potjie No.3",
    brand: "Hart",
    category: "pots-pans",
    description:
      "Pre-seasoned three-legged cast iron potjie. Feeds 8–10 people and gets better every single time you cook in it.",
    details: ["Pre-seasoned cast iron", "Serves 8–10", "Lid with lifting handle", "Open fire & coals ready"],
    images: [29685081, 16927367],
    sizeSet: "one",
    colorway: "Cast Iron Black",
    price: 1499,
    rating: 4.9,
    reviews: 118,
    stock: 22,
    featured: true,
    sold: 289,
  },
  {
    slug: "tefal-non-stick-deep-skillet",
    name: "Tefal Non-Stick Deep Skillet 30cm",
    brand: "Tefal",
    category: "pots-pans",
    description:
      "Deep 30cm pan with the Thermo-Spot heat indicator and a non-stick coating that actually lasts.",
    details: ["30cm deep pan", "Thermo-Spot indicator", "Titanium non-stick coating", "Oven safe to 175°C"],
    images: [29684979, 7111399],
    sizeSet: "one",
    colorway: "Black",
    price: 899,
    rating: 4.7,
    reviews: 74,
    stock: 30,
    sold: 187,
  },
  {
    slug: "snappy-chef-stovetop-coffee-pot",
    name: "Matte Black Stovetop Coffee Pot",
    brand: "Snappy Chef",
    category: "pots-pans",
    description:
      "Six-cup stovetop percolator in matte black. Proper coffee without the machine price tag.",
    details: ["6-cup capacity", "Heat-resistant handle", "Aluminium body", "Gas, electric & induction"],
    images: [37552794],
    sizeSet: "one",
    colorway: "Matte Black",
    price: 649,
    rating: 4.6,
    reviews: 58,
    stock: 26,
    isNew: true,
    sold: 121,
  },
  {
    slug: "sheffield-chef-knife-set",
    name: "Sheffield Professional Chef Knife Set",
    brand: "Sheffield",
    category: "pots-pans",
    description:
      "Six forged stainless steel knives with a magnetic block. Balanced, sharp and built for daily cooking.",
    details: ["6 forged knives", "Magnetic wooden block", "Full-tang construction", "Hand wash recommended"],
    images: [30327171],
    sizeSet: "one",
    colorway: "Steel / Walnut",
    price: 1299,
    rating: 4.8,
    reviews: 41,
    stock: 14,
    sold: 83,
  },
  {
    slug: "sheffield-24-piece-dinner-set",
    name: "Sheffield 24-Piece Dinner Set",
    brand: "Sheffield",
    category: "pots-pans",
    description:
      "Service for six in matte-glazed stoneware — dinner plates, side plates, bowls and mugs. Chip resistant.",
    details: ["Service for 6", "Matte-glazed stoneware", "Microwave & dishwasher safe", "Packed in a gift carton"],
    images: [6448484],
    sizeSet: "one",
    colorway: "Cream",
    price: 1199,
    was: 1499,
    rating: 4.7,
    reviews: 66,
    stock: 18,
    sold: 143,
  },

  // ---------------- FURNITURE ----------------
  {
    slug: "coricraft-oak-six-seater-table",
    name: "Solid Oak 6-Seater Dining Table",
    brand: "Coricraft",
    category: "furniture",
    description:
      "A proper family table in solid kiln-dried oak with a hand-oiled finish. Delivered assembled to your door.",
    details: ["Solid kiln-dried oak", "Seats 6 comfortably", "Hand-oiled natural finish", "Delivered assembled"],
    images: [5262675, 22696775],
    sizeSet: "one",
    colorway: "Natural Oak",
    price: 11999,
    was: 13999,
    rating: 4.9,
    reviews: 27,
    stock: 4,
    featured: true,
    sold: 38,
  },
  {
    slug: "marble-top-dining-table",
    name: "Marble-Top Dining Table",
    brand: "Coricraft",
    category: "furniture",
    description:
      "Honed marble top on a sculpted base. The centrepiece of a serious dining room — heavy, cool and gorgeous.",
    details: ["Honed natural marble top", "Sculpted powder-coated base", "Seats 6–8", "Sealed against staining"],
    images: [22696776, 22696775],
    sizeSet: "one",
    colorway: "White Marble",
    price: 14499,
    rating: 4.8,
    reviews: 15,
    stock: 3,
    isNew: true,
    sold: 19,
  },
  {
    slug: "scandi-four-seater-dining-set",
    name: "Scandi 4-Seater Dining Set",
    brand: "Mr Home",
    category: "furniture",
    description:
      "Compact table plus four moulded chairs — perfect for a flat or a starter home. Flat-packed with tools included.",
    details: ["Table + 4 chairs", "Beech legs, moulded seats", "Compact 120cm top", "Easy 30-minute assembly"],
    images: [12548694, 16799769],
    sizeSet: "one",
    colorway: "Oak / Grey",
    price: 7499,
    was: 8499,
    rating: 4.6,
    reviews: 33,
    stock: 6,
    sold: 52,
  },
  {
    slug: "solid-wood-console-table",
    name: "Solid Wood Console Table",
    brand: "Mr Home",
    category: "furniture",
    description:
      "Narrow console for an entrance hall or behind the couch. Solid timber top with a slim steel frame.",
    details: ["Solid timber top", "Powder-coated steel frame", "110cm x 35cm", "Levelling feet"],
    images: [9290603],
    sizeSet: "one",
    colorway: "Walnut / Black",
    price: 3499,
    rating: 4.7,
    reviews: 24,
    stock: 9,
    sold: 44,
  },
  {
    slug: "stackable-dining-chairs-set-of-4",
    name: "Stackable Dining Chairs (Set of 4)",
    brand: "Mr Home",
    category: "furniture",
    description:
      "Four cushioned stackable chairs that tuck away when the family leaves. Sturdy steel frames, easy-clean fabric.",
    details: ["Set of 4 chairs", "Stackable steel frames", "Easy-clean upholstery", "120kg weight rating"],
    images: [13045981],
    sizeSet: "one",
    colorway: "Charcoal",
    price: 2899,
    was: 3399,
    rating: 4.5,
    reviews: 31,
    stock: 12,
    sold: 67,
  },
];
